package lab11_selenium;
import org.testng.Assert;
//Generated by Selenium IDE
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Parameters;
//import static org.hamcrest.CoreMatchers.is;
//import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
class Lab4Test {
private WebDriver driver;
private Map<String, Object> vars;
JavascriptExecutor js;
@BeforeMethod
//@Parameters("browser")
public void setUp() {

		WebDriverManager.chromedriver().setup();
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();

 }
@AfterMethod
public void tearDown() {
 driver.quit();
}
@Test
public void lab4() {
 driver.get("https://tutorialsninja.com/demo/index.php");

 homepage obj=new homepage(driver);
 obj.clickDesktops();
 obj.clickMac();

 obj.selectSortAZ();
 obj.clickAddToCart();

 obj.searchProduct("Mobile");
 obj.enableDescriptionSearch();
 obj.confirmSearch();

 obj.searchProduct("Monitors");
}
}

